name: CI # ci文件的名字

env:
  CI: true

on:
  push:
    branches: [ main ] # 触发CI的条件

permissions: 
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains a single job called "build"
jobs: # CI/CD通过执行一个个的Job来完成每个阶段的工作，这里配置每个Jobs
  Check: # Job的名称
    runs-on: ubuntu-latest # Runner，github托管的虚拟机环境，用来执行下面的Job命令
    steps: # 执行步骤
    - name: 'checkout' # 子步骤名称
      uses: actions/checkout@v3 # 使用的action，检出分支，可以使用docker hub中的镜像：docker://alpine:3.8

    - name: Use Node.js 16 # ESLint 检测代码质量
      uses: actions/setup-node@v3 # 使用node环境
      with:
        node-version: 16
    # - run: npm # 执行命令安装依赖，也可以执行shell脚本./.github/scripts/build.sh
    - run: npm install -g eslint && eslint $GITHUB_WORKSPACE/src/*/**.tsx # 安装全局ESLint并检测代码

    # - name: StyleLintCode # 检测代码样式
    #   uses: actions/setup-node@v2 # 使用node环境
    # - run: yarn
    # - run: npm install -g stylelint stylelint-less
    # - run: stylelint ../../src/*/**.less # 执行检测命令
    # - run: mkdir .tmp-css-check && touch .tmp-css-check/.stylelintrc.json && echo '{"plugins":["stylelint-less"],"rules":{}}' >> .tmp-css-check/.stylelintrc.json && stylelint "src/**/*.less" --config .tmp-css-check/.stylelintrc.json --aei

  Build: # Job名称
    needs: Check # 决定执行的顺序，通过needs，在Check任务执行完成后执行当前任务，指出数组，可以写入多个
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps: # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
      - run: npm
      - run: npm run build    
  # Deploy:
  #  needs: Check
  # # The type of runner that the job will run on
  #  runs-on: ubuntu-latest

  # # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
  #  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #   - name: checkout
  #     uses: actions/checkout@v2

  #  # Runs a single command using the runners shell
  #   - name: build
  #     uses: actions/setup-node@v2
  #     env:
  #       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  #       BRANCH: main
  #   - run: yarn
  #   - run: yarn build:prod

  #   - name: deploy
  #     uses: JamesIves/github-pages-deploy-action@v4.3.3
  #     with:
  #       branch: gh-pages
  #       folder: build
